apiVersion: v1
entries:
  sto-manager:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-08-16T13:17:00.328566-04:00"
    dependencies:
    - name: harness-common
      repository: https://harness.github.io/helm-common/charts
      version: 0.1.1
    description: A Helm chart for Kubernetes
    digest: 5a7218b3041273574e716f5f4ed40c9774a0ce4d5070f57a3771a0dcaeb4cf31
    name: sto-manager
    type: application
    urls:
    - sto-manager-0.1.0.tgz
    version: 0.1.0
generated: "2022-08-16T13:17:00.327013-04:00"
